### ISSUE TITLE
obsplus 0.1.0 planning

### ISSUE THREAD

**Issue by d-chambers** [niosh-mining/obsplus#119]
This PR is intended to help organize our efforts for the obsplus 0.1.0 release. Primarily, we need shift obsplus and its development from a "prototype" mindset to that of a "real" package since it has proven its usefulness and viability. 

Before 0.1.0
----------------
- [x] Consider spinning all the xarray functionality off into its own package and replace it with the waveform dataframe work from [mopy](github.com/seismopy/mopy)
- [x] Implement validators described by #91.
- [x] Revamp the docs, add a quick start and get feedback from users. 
- [x] Nail down how dataframe converters **should** work. Create a document of guiding principles/design specs for such conversions.
- [x] Decide on official date/time representations (#88) for dataframes.  
- [x] Implement code linting complementary to black (line length, ordered imports, etc.) using flake 8 or the like.
- [x] Change schema of banks to use an int representation of times in their respective databases.
- [x] Look into adding byte start/end columns for partial file reads.
- [x] Add windows support (#149).
- [x] Maybe rename datasets to indicate testing status (#148).

After/During 0.1.0
--------------------------
- [ ] Adopt [git flow](https://nvie.com/posts/a-successful-git-branching-model/), or at least come to a consensus on a branching model.
- [x] Update and expand the contributing document.
- [x] Release obsplus conda package.
- [x] Create a publication on obsplus, either SRL or JOSS.

**Comment by d-chambers** [comment]
Comment by @El-minadero:

I like the idea of spinning off xarray functions into its own package. Based on my experience using xarray for computations, I have some thoughts on standards for a stream->xarray conversion:

* Separate 'Network' and 'Station' coordinates make for an incredibly sparse tensor, so a 'Network.Station' coordinate makes a lot of sense. 
* Separating Channel into its own coordinate vs a 'Network.Station.Channel' makes it much easier to slice through relevant sections of the dataset. A way of transforming coordinates between Absolute North, East, Z; Magnetic North, East; Radial, Transverse, Z, would have great utility.
* The .attrs metatadata attribute gets incredibly busy, especially when containing an ordered dict that refers to every individual channel. Assuming that each channel is sampled at the same rate, one alternative would be to use registered accessors http://xarray.pydata.org/en/stable/internals.html#variable-objects, for seismology specific attributes. I've been toying with the idea of making separate accessors for latitude, longitude, elevation (or alternatively UTM data), which are themselves just smaller xarrays. This might make transforming channel directions, reprojecting spatial coordinates, and plotting arrays/events in space greatly simplified. 
* Another attribute which auto-chunks the xarray based on time coordinate transformations (e.g. give me chunks of 100s -> chunk size of 10,000 based on a channel sampling rate of 10hz).

**Comment by d-chambers** [comment]
@El-minadero,

A few thoughts,

## Why not keep Xarray in ObsPlus?

I should elaborate on why I want to spin the xarray stuff out of obsplus. The main reason is that it is a bit heavy for our use cases so far and I don't really want to maintain something so ambitious that we aren't using. Xarray is certainly powerful, but the APIs are a bit clunky (compared to pandas) and there is a lot of work to be done in order to figure out how seismic data *should* be represented in xarray data structures in order to follow the [cf specs for time-series data](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#discrete-sampling-geometries). It certainly requires more attention than simply being a side-thought in Obsplus. 

That being said, I think there is a lot of potential for xarray/seismic data. Xarray is probably the easiest path for unlocking efficient big data/cloud computing for seismology in python, but again, I feel it deserves its own package as it will take a lot of effort to get right.  

 For lighter use cases (ie those obsplus aims to support), I am leaning towards a dataframe-based `Stream`-like object. It contains one dataframe for timeseries data and one for stats. This approach still provides some of the xarray advantages while offering the familiarity and polish of the pandas API. It also feels more natural since obsplus is advertised as  "pandas-centric" rather than "xarray-centric". Moreover, xarray adds a lot of dependencies to obsplus, so it will be nice to get rid of those.  

# Moving forward

I  think we need  a different place to discuss design specs and such since xarray will fall outside of obsplus' scope. I know @jkmacc-LANL is thinking about this is as well. Maybe we can get something set up in the next few weeks for this purpose.

**Comment by jkmacc-LANL** [comment]
👍 working on a notebook exploring this topic, and hope to have something to share soon.

**Comment by jkmacc-LANL** [comment]
Just got a green light to share some thoughts.  Will send soon.  Ok if I invite a couple of other interested folks to discuss (not on this issue)?  One is quite familiar with xarray.

**Comment by d-chambers** [comment]
Absolutely 👍

**Comment by d-chambers** [comment]
>Just got a green light to share some thoughts. Will send soon. Ok if I invite a couple of other interested folks to discuss (not on this issue)? One is quite familiar with xarray.

Any updates on this @jkmacc-LANL ?

**Comment by d-chambers** [comment]
I decided to work on getting 0.1.0 out before finishing the `WaveFrame` stuff. It may or may not live in `ObsPlus`, I need more time to ruminate on it.

**Comment by d-chambers** [comment]
update: ObsPlus 0.0.6 is now on Conda. I think waiting to release 0.1.0 until ObsPy 1.2.0 is out would be desirable so we can use it as a dependency.
