### ISSUE TITLE
Version 0.0.1 Checklist

### ISSUE THREAD

**Issue by d-chambers** [niosh-mining/obsplus#81]
This is a checklist for releasing to 0.0.1. Please feel free to edit.

- [x] Finish and Merge (#79 / #29)
- [ ] Rethink validators, perhaps follow (https://github.com/obspy/obspy/issues/2154) to address #64. If it works well push it to Obspy 2.0.0 
- [x] Finish and Merge (#73)
- [ ] Switch CI to Azure pipelines, automate release to PyPI based on git version tag, [here](https://medium.com/@anthonypjshaw/azure-pipelines-with-python-by-example-aa65f4070634) is a good starting point. Setup tests for OsX and Windows in addition to the ones running for linux. 

[PRs related to 0.0.1](https://github.com/niosh-mining/obsplus/pulls?q=is%3Aopen+is%3Apr+milestone%3A0.0.1)
[Issues related to 0.0.1](https://github.com/niosh-mining/obsplus/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.0.1)

**Comment by sboltz** [comment]
This looks like a good checklist to me. I am hopefully going to try to tackle your comments on #79 and #73 at some point this week.

**Comment by d-chambers** [comment]
Ok I punted on some of these so we can do a release.

checklist:
[ ] make version tag 
[ ] publish/run new docs
[ ] upload to PyPi
